modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"

[[mods]]
    modId="armorstatushud"
    version="1.5.2"
    displayName="Armor Status HUD"
    updateJSONURL="https://minecraft.darkboy.ru/api/check-mod-updates/armorstatushud.json"
    displayURL="https://minecraft.darkboy.ru/mods/armorstatushud"
    credits="Inspired by the armor/item tags available in IngameInfo by DaftPVF"
    authors="bspkrs, Bobsans"
    description='''Provides a HUD with your equipped armor/item stats.'''

    [[dependencies.armorstatushud]]
        modId="forge"
        mandatory=true
        versionRange="[44,)"
        ordering="NONE"
        side="BOTH"

    [[dependencies.armorstatushud]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.19.3,1.20)"
        ordering="NONE"
        side="BOTH"

    [[dependencies.armorstatushud]]
        modId="boblib"
        mandatory=true
        versionRange="[0.3.2,)"
        ordering="NONE"
        side="BOTH"
