modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
    modId="armorstatushud"
    version="1.4.0"
    displayName="Armor Status HUD"
    updateJSONURL="https://minecraft.darkboy.ru/api/check-mod-updates/armorstatushud.json"
    displayURL="https://minecraft.darkboy.ru/mods/armorstatushud"
    credits="Inspired by the armor/item tags available in IngameInfo by DaftPVF"
    authors="bspkrs, Bobsans"
    description='''Provides a HUD with your equipped armor/item stats.'''

    [[dependencies.armorstatushud]]
        modId="forge"
        mandatory=true
        versionRange="[36,)"
        ordering="NONE"
        side="BOTH"

    [[dependencies.armorstatushud]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.16.5,1.17)"
        ordering="NONE"
        side="BOTH"

    [[dependencies.armorstatushud]]
        modId="boblib"
        mandatory=true
        versionRange="[0.2.0,)"
        ordering="NONE"
        side="BOTH"
