modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
    modId="armorstatushud"
    version="1.3.0"
    displayName="Armor Status HUD"
    updateJSONURL="https://minecraft.darkboy.ru/api/check-mod-updates/armorstatushud.json"
    displayURL="http://www.minecraftforum.net/topic/1114612-/"
    credits="Inspired by the armor/item tags available in IngameInfo by DaftPVF."
    authors="bspkrs, Bobsans"
    description='''Provides a HUD with your equipped armor/item stats.'''

    [[dependencies.armorstatushud]]
        modId="forge"
        mandatory=true
        versionRange="[28,)"
        ordering="NONE"
        side="BOTH"

    [[dependencies.armorstatushud]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.14.4]"
        ordering="NONE"
        side="BOTH"
